using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.CartridgeLoader.Cartridges;
using Content.Shared.CriminalRecords.Systems;
using Content.Shared.Security;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class WantedListUiFragment : BoxContainer
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    private readonly SpriteSystem _spriteSystem;

    private string? _selectedTargetName;
    private List<WantedRecord> _wantedRecords = new();

    // OSK weapon registry page state.
    private string? _selectedSerial;
    private List<WeaponRegistryEntry> _registryEntries = new();

    // Raised with (serial, owner). Null owner means "clear the owner name".
    public event Action<string, string?>? OnOwnerSaved;

    // Raised when the player switches to the registry page, so WantedListUi can
    // ask the server to re-send the current registry snapshot.
    public event Action? OnRegistryRefresh;

    public WantedListUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();

        SearchBar.OnTextChanged += OnSearchBarTextChanged;
        RegistrySearchBar.OnTextChanged += OnRegistrySearchTextChanged;
        RegistryNavButton.OnPressed += _ => ShowRegistry(true);
        RegistryBackButton.OnPressed += _ => ShowRegistry(false);
        SaveOwnerButton.OnPressed += _ => SaveOwner();
        OwnerEdit.OnTextEntered += _ => SaveOwner();
    }

    private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
    {
        var found = !String.IsNullOrWhiteSpace(args.Text)
            ? _wantedRecords.FindAll(r =>
                r.TargetInfo.Name.Contains(args.Text) ||
                r.Status.ToString().Contains(args.Text, StringComparison.OrdinalIgnoreCase))
            : _wantedRecords;

        UpdateState(found, false);
    }

    public void UpdateState(List<WantedRecord> records, bool refresh = true)
    {
        if (records.Count == 0)
        {
            NoRecords.Visible = true;
            RecordsList.Visible = false;
            RecordUnselected.Visible = false;
            PersonContainer.Visible = false;

            _selectedTargetName = null;
            if (refresh)
                _wantedRecords.Clear();

            RecordsList.PopulateList(new List<ListData>());

            return;
        }

        NoRecords.Visible = false;
        RecordsList.Visible = true;
        RecordUnselected.Visible = true;
        PersonContainer.Visible = false;

        var dataList = records.Select(r => new StatusListData(r)).ToList();

        RecordsList.GenerateItem = GenerateItem;
        RecordsList.ItemPressed = OnItemSelected;
        RecordsList.PopulateList(dataList);

        if (refresh)
            _wantedRecords = records;
    }

    private void OnItemSelected(BaseButton.ButtonEventArgs args, ListData data)
    {
        if (data is not StatusListData(var record))
            return;

        FormattedMessage GetLoc(string fluentId, params (string,object)[] args)
        {
            var msg = new FormattedMessage();
            var fluent = Loc.GetString(fluentId, args);
            msg.AddMarkupPermissive(fluent);
            return msg;
        }

        // Set personal info
        PersonName.Text = record.TargetInfo.Name;
        TargetAge.SetMessage(GetLoc(
            "wanted-list-age-label",
            ("age", record.TargetInfo.Age)
        ));
        TargetJob.SetMessage(GetLoc(
            "wanted-list-job-label",
            ("job", record.TargetInfo.JobTitle.ToLower())
        ));
        TargetSpecies.SetMessage(GetLoc(
            "wanted-list-species-label",
            ("species", record.TargetInfo.Species.ToLower())
        ));
        TargetGender.SetMessage(GetLoc(
            "wanted-list-gender-label",
            ("gender", record.TargetInfo.Gender)
        ));
        // Radiant sector  start
        TargetShuttle.SetMessage(GetLoc(
            "wanted-list-shuttle-label",
            ("shuttle", string.IsNullOrWhiteSpace(record.TargetInfo.RegisteredShuttle)
                ? Loc.GetString("wanted-list-no-shuttle-label")
                : record.TargetInfo.RegisteredShuttle))
        // Radiant sector  end
        );

        // Set reason
        WantedReason.SetMessage(GetLoc(
            "wanted-list-reason-label",
            ("reason", record.Reason ?? Loc.GetString("wanted-list-unknown-reason-label"))
        ));

        // Set status
        PersonState.SetMessage(GetLoc(
            "wanted-list-status-label",
            ("status", record.Status.ToString().ToLower())
        ));

        // Set initiator
        InitiatorName.SetMessage(GetLoc(
            "wanted-list-initiator-label",
            ("initiator", record.Initiator ?? Loc.GetString("wanted-list-unknown-initiator-label"))
        ));

        // History table
        // Clear table if it exists
        HistoryTable.RemoveAllChildren();

        HistoryTable.AddChild(new Label()
        {
            Text = Loc.GetString("wanted-list-history-table-time-col"),
            StyleClasses = { "LabelSmall" },
            HorizontalAlignment = HAlignment.Center,
        });
        HistoryTable.AddChild(new Label()
        {
            Text = Loc.GetString("wanted-list-history-table-reason-col"),
            StyleClasses = { "LabelSmall" },
            HorizontalAlignment = HAlignment.Center,
            HorizontalExpand = true,
        });

        HistoryTable.AddChild(new Label()
        {
            Text = Loc.GetString("wanted-list-history-table-initiator-col"),
            StyleClasses = { "LabelSmall" },
            HorizontalAlignment = HAlignment.Center,
        });

        if (record.History.Count > 0)
        {
            HistoryTable.Visible = true;

            foreach (var history in record.History.OrderByDescending(h => h.AddTime))
            {
                HistoryTable.AddChild(new Label()
                {
                    Text = $"{history.AddTime.Hours:00}:{history.AddTime.Minutes:00}:{history.AddTime.Seconds:00}",
                    StyleClasses = { "LabelSmall" },
                    VerticalAlignment = VAlignment.Top,
                });

                HistoryTable.AddChild(new RichTextLabel()
                {
                    Text = $"[color=white]{history.Crime}[/color]",
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Top,
                    StyleClasses = { "LabelSubText" },
                    Margin = new(10f, 0f),
                });

                HistoryTable.AddChild(new RichTextLabel()
                {
                    Text = $"[color=white]{history.InitiatorName}[/color]",
                    StyleClasses = { "LabelSubText" },
                    VerticalAlignment = VAlignment.Top,
                });
            }
        }

        RecordUnselected.Visible = false;
        PersonContainer.Visible = true;

        // Save selected item
        _selectedTargetName = record.TargetInfo.Name;
    }

    private void GenerateItem(ListData data, ListContainerButton button)
    {
        if (data is not StatusListData(var record))
            return;

        var box = new BoxContainer() { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true };
        var label = new Label() { Text = record.TargetInfo.Name };
        var rect = new TextureRect()
        {
            TextureScale = new(2.2f),
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Center,
            Margin = new(0f, 0f, 6f, 0f),
        };

        if (record.Status is not SecurityStatus.None)
        {
            var proto = "SecurityIcon" + record.Status switch
            {
                SecurityStatus.Detained => "Incarcerated",
                _ => record.Status.ToString(),
            };

            if (_prototypeManager.TryIndex<SecurityIconPrototype>(proto, out var prototype))
            {
                rect.Texture = _spriteSystem.Frame0(prototype.Icon);
            }
        }

        box.AddChild(rect);
        box.AddChild(label);
        button.AddChild(box);
        button.AddStyleClass(ListContainer.StyleClassListContainerButton);

        if (record.TargetInfo.Name.Equals(_selectedTargetName))
        {
            button.Pressed = true;
            // For some reason the event is not called when `Pressed` changed, call it manually.
            OnItemSelected(
                new(button, new(new(), BoundKeyState.Down, new(), false, new(), new())),
                data);
        }
    }

    /// <summary>
    ///     Switches between the wanted list page and the weapon registry page.
    /// </summary>
    private void ShowRegistry(bool show)
    {
        WantedPage.Visible = !show;
        RegistryPage.Visible = show;
        if (show)
        {
            // Ask the server for the current registry. This happens when the window
            // is already open and the fragment attached, so the answer is guaranteed
            // to arrive and the list is never stale/empty on a fresh open.
            OnRegistryRefresh?.Invoke();
            UpdateRegistry(_registryEntries, false); // re-render from cached data
        }
    }

    /// <summary>
    ///     Renders the registry entries pushed by WeaponSerialSystem.
    /// </summary>
    public void UpdateRegistry(List<WeaponRegistryEntry> entries, bool refresh = true)
    {
        if (refresh)
        {
            _registryEntries = entries.DistinctBy(e => e.Serial).ToList();

            // A fresh server snapshot while an entry is selected (e.g. right after an
            // owner name was saved) must refresh the detail pane too, otherwise the
            // owner label would keep showing the previous value until re-selection.
            if (_selectedSerial is { } serial
                && _registryEntries.FirstOrDefault(e => e.Serial == serial) is { } updated)
            {
                RenderRegistryDetail(updated);
            }
        }

        // Re-render goes through the search filter: if the player is mid-search,
        // a pushed server update or a page switch must not reset their filter.
        RenderRegistry(FilterRegistry(RegistrySearchBar.Text));
    }

    /// <summary>
    ///     Client-side filtering. The whole registry is already in memory, so there
    ///     is no reason to round-trip the server just to narrow the list.
    /// </summary>
    private List<WeaponRegistryEntry> FilterRegistry(string? text)
    {
        if (String.IsNullOrWhiteSpace(text))
            return _registryEntries;

        return _registryEntries.FindAll(e =>
            e.Serial.Contains(text, StringComparison.OrdinalIgnoreCase) ||
            e.Name.Contains(text, StringComparison.OrdinalIgnoreCase) ||
            (e.Owner != null && e.Owner.Contains(text, StringComparison.OrdinalIgnoreCase)) ||
            e.Rarity.ToString().Contains(text, StringComparison.OrdinalIgnoreCase));
    }

    private void OnRegistrySearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        // args.Text, not RegistrySearchBar.Text: the event args carry the exact
        // value at the moment of the event, which is the honest source here.
        RenderRegistry(FilterRegistry(args.Text));
    }

    /// <summary>
    ///     Draws the given subset of entries and picks the right "empty" message:
    ///     the registry has no weapons at all vs. the filter matched nothing.
    /// </summary>
    private void RenderRegistry(List<WeaponRegistryEntry> toShow)
    {
        RegistryList.GenerateItem = GenerateRegistryItem;
        RegistryList.ItemPressed = OnRegistryItemSelected;
        var dataList = new List<ListData>();
        foreach (var entry in toShow)
            dataList.Add(new WeaponRegistryListData(entry));
        RegistryList.PopulateList(dataList);

        var empty = toShow.Count == 0;
        var filterActive = !String.IsNullOrWhiteSpace(RegistrySearchBar.Text);
        NoRegistryEntries.Visible = empty && !filterActive;
        NoRegistryMatches.Visible = empty && filterActive;
        RegistryList.Visible = !empty;
        if (empty)
        {
            RegistryDetail.Visible = false;
            _selectedSerial = null;
        }
    }

    private void OnRegistryItemSelected(BaseButton.ButtonEventArgs args, ListData data)
    {
        if (data is not WeaponRegistryListData(var entry))
            return;

        _selectedSerial = entry.Serial;
        RenderRegistryDetail(entry);
    }

    private void RenderRegistryDetail(WeaponRegistryEntry entry)
    {
        DetailWeapon.SetMessage(BuildMessage("weapon-registry-detail-weapon", ("name", entry.Name)));
        DetailSerial.SetMessage(BuildMessage("weapon-registry-detail-serial", ("serial", entry.Serial)));
        // The loc keys are lowercase-first while enum members start with an upper-case
        // letter (e.g. UniqueWrittenoff -> uniqueWrittenoff), so fold the first character.
        var rarity = entry.Rarity.ToString();
        var rarityName = string.Concat(rarity.Substring(0, 1).ToLowerInvariant(), rarity.Substring(1));
        var rarityKey = string.Concat("weapon-registry-rarity-", rarityName);
        DetailRarity.SetMessage(BuildMessage(rarityKey));
        DetailOwner.SetMessage(entry.Owner == null
            ? BuildMessage("weapon-registry-detail-owner-unset")
            : BuildMessage("weapon-registry-detail-owner-set", ("owner", entry.Owner)));

        // Pre-fill the field: clearing it and pressing save removes the owner.
        OwnerEdit.Text = entry.Owner ?? string.Empty;

        RegistryDetail.Visible = true;
    }

    private void GenerateRegistryItem(ListData data, ListContainerButton button)
    {
        if (data is not WeaponRegistryListData(var entry))
            return;

        button.AddChild(new Label() { Text = entry.Serial, ClipText = true });
        button.AddStyleClass(ListContainer.StyleClassListContainerButton);

        if (entry.Serial.Equals(_selectedSerial))
        {
            button.Pressed = true;
            // Same workaround as the wanted list: Pressed change does not raise the event.
            OnRegistryItemSelected(
                new(button, new(new(), BoundKeyState.Down, new(), false, new(), new())),
                data);
        }
    }

    private void SaveOwner()
    {
        if (_selectedSerial == null)
            return;

        var text = OwnerEdit.Text.Trim();
        OnOwnerSaved?.Invoke(_selectedSerial, string.IsNullOrEmpty(text) ? null : text);
    }

    private FormattedMessage BuildMessage(string fluentId, params (string, object)[] args)
    {
        var msg = new FormattedMessage();
        msg.AddMarkupPermissive(Loc.GetString(fluentId, args));
        return msg;
    }
}

internal record StatusListData(WantedRecord Record) : ListData;

internal record WeaponRegistryListData(WeaponRegistryEntry Entry) : ListData;
