using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Weapons.Components;
using Content.Shared._radiant.WeaponSerial;
using Content.Shared.Weapons.Ranged.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Log;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._radiant.WeaponSerial;

[GenerateTypedNameReferences]
public sealed partial class WeaponRegistryUiFragment : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IComponentFactory _componentFactory = default!;

    // How many entries one page holds. The whole registry already lives in memory,
    // so paging is pure client-side slicing; 10 keeps the page readable inside the
    // PDA program area.
    private const int PageSize = 10;

    // Side of the square icon box of a list row: the DEFAULT icon size. Every
    // weapon sprite is normalised into it, whatever its source texture is — a
    // bigger one is scaled down, a smaller one is scaled up, and a sprite drawn
    // with a scale factor (TextureScale 1.8f and the like) still lands exactly
    // here. Two reasons it must be this strict:
    //   1. ListContainer measures the height of the FIRST row and reuses it for
    //      all the others, so one row with a bigger icon would overlap its
    //      neighbours.
    //   2. Rows then all look the same, instead of mixing huge and tiny icons.
    private const float IconBoxSize = 32f;

    // Third line of a row when the weapon has no owner yet. It must not be an
    // empty string: an empty Label measures as ZERO height (the font metrics are
    // skipped for empty text), and then rows with and without an owner would end
    // up different heights — the very thing the fixed icon box prevents.
    private const string NoOwnerPlaceholder = "—";

    // Same zero-height reason as NoOwnerPlaceholder, but for the DETAIL pane:
    // a line whose value is missing (owner, caliber) shows a dash instead.
    private const string MissingValueText = "—";

    private string? _selectedSerial;
    private List<WeaponRegistryEntry> _registryEntries = new();
    private int _page;

    // Current order of the list. The default is the order the server sent, which
    // is "the moment the weapon appeared in the registry, newest first".
    private WeaponRegistrySortMode _sortMode = WeaponRegistrySortMode.DateAdded;

    // The little sorting window that pops up OVER the PDA window. It is parented
    // to the UI modal root (not to us), so it floats above everything and closes
    // on a click outside; we own its lifetime and tidy it up in ExitedTree.
    private WeaponRegistryFilterPopup _filterPopup = default!;

    // NOTE: the PDA is read-only — the owner is entered only in the weapon
    // registration console. OnOwnerSaved and SaveOwner were removed deliberately.
    public WeaponRegistryUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RegistrySearchBar.OnTextChanged += OnRegistrySearchTextChanged;
        RegistryPrevPageButton.OnPressed += _ => ChangePage(-1);
        RegistryNextPageButton.OnPressed += _ => ChangePage(1);
        RegistryFilterButton.OnPressed += _ => OpenFilterPopup();

        _filterPopup = new WeaponRegistryFilterPopup();
        UserInterfaceManager.ModalRoot.AddChild(_filterPopup);
        _filterPopup.OnSortSelected += OnSortModeSelected;

        UpdateFilterButtonTooltip();
    }

    /// <summary>
    ///     Renders the registry entries pushed by WeaponSerialSystem.
    /// </summary>
    public void UpdateRegistry(List<WeaponRegistryEntry> entries, bool refresh = true)
    {
        if (refresh)
        {
            _registryEntries = entries.DistinctBy(e => e.Serial).ToList();

            // A fresh server snapshot while an entry is selected (e.g. right after an
            // owner name was saved) must refresh the detail pane too, otherwise the
            // owner label would keep showing the previous value until re-selection.
            if (_selectedSerial is { } serial
                && _registryEntries.FirstOrDefault(e => e.Serial == serial) is { } updated)
            {
                RenderRegistryDetail(updated);
            }
        }

        // Re-render goes through the search filter: if the player is mid-search,
        // a pushed server update must not reset their filter.
        RenderRegistry(BuildList());
    }

    /// <summary>
    ///     Client-side filtering. The whole registry is already in memory, so there
    ///     is no reason to round-trip the server just to narrow the list.
    /// </summary>
    private List<WeaponRegistryEntry> FilterRegistry(string? text)
    {
        if (String.IsNullOrWhiteSpace(text))
            return _registryEntries;

        return _registryEntries.FindAll(e =>
            e.Serial.Contains(text, StringComparison.OrdinalIgnoreCase) ||
            e.Name.Contains(text, StringComparison.OrdinalIgnoreCase) ||
            (e.Owner != null && e.Owner.Contains(text, StringComparison.OrdinalIgnoreCase)));
    }

    /// <summary>
    ///     The list the program actually shows: the search filter plus the order
    ///     the player picked in the sorting window. Both happen client-side — the
    ///     whole registry is already in memory, so this needs no server trip.
    /// </summary>
    private List<WeaponRegistryEntry> BuildList() => SortRegistry(FilterRegistry(RegistrySearchBar.Text));

    /// <summary>
    ///     Orders the filtered entries.
    ///     The server order (newest first) is the default and also the fallback:
    ///     every other mode sorts a COPY, so picking "by name" and then going back
    ///     to "newest first" returns the server order exactly.
    /// </summary>
    private List<WeaponRegistryEntry> SortRegistry(List<WeaponRegistryEntry> entries)
    {
        if (_sortMode == WeaponRegistrySortMode.DateAdded)
            return entries;

        var sorted = new List<WeaponRegistryEntry>(entries);

        switch (_sortMode)
        {
            case WeaponRegistrySortMode.NameAscending:
                SortByKey(sorted, e => e.Name, descending: false);
                break;
            case WeaponRegistrySortMode.NameDescending:
                SortByKey(sorted, e => e.Name, descending: true);
                break;
            case WeaponRegistrySortMode.Caliber:
                SortByKey(sorted, GetCaliberKey, descending: false);
                break;
            case WeaponRegistrySortMode.WeaponClass:
                SortByKey(sorted, GetWeaponClassKey, descending: false);
                break;
            case WeaponRegistrySortMode.Serial:
                SortByKey(sorted, e => e.Serial, descending: false);
                break;
        }

        return sorted;
    }

    /// <summary>
    ///     Sorts by a text key read out of an entry.
    /// </summary>
    private static void SortByKey(List<WeaponRegistryEntry> entries,
        Func<WeaponRegistryEntry, string?> getKey,
        bool descending)
    {
        entries.Sort((a, b) =>
        {
            var order = CompareKeys(getKey(a), getKey(b), descending);

            // List.Sort is NOT stable: two weapons with the same name would swap
            // places between renders (even between two identical sorts). The serial
            // is unique, so using it as a tie-breaker makes the order total.
            return order != 0 ? order : String.Compare(a.Serial, b.Serial, StringComparison.Ordinal);
        });
    }

    /// <summary>
    ///     Compares two keys, putting "no data" at the bottom.
    /// </summary>
    private static int CompareKeys(string? left, string? right, bool descending)
    {
        var leftMissing = String.IsNullOrWhiteSpace(left);
        var rightMissing = String.IsNullOrWhiteSpace(right);

        // A dash is not a value: an entry without a name/caliber sinks to the BOTTOM
        // in both directions, it is never "the last name in the alphabet".
        if (leftMissing || rightMissing)
            return leftMissing == rightMissing ? 0 : leftMissing ? 1 : -1;

        // InvariantCulture: proper alphabetical order for Latin AND Cyrillic names,
        // and identical on every machine (the OS locale must not leak into the
        // order, or two players would see two different lists).
        var result = String.Compare(left, right, StringComparison.InvariantCultureIgnoreCase);
        return descending ? -result : result;
    }

    /// <summary>
    ///     Caliber of the weapon, the way the player sees it on examine. The
    ///     registry entry carries only the prototype id, so the caliber is read from
    ///     the prototype (GunComponent.ExamineCaliber is a fluent id, hence the
    ///     localization: the list is sorted by what is actually on the screen).
    /// </summary>
    private string? GetCaliberKey(WeaponRegistryEntry entry)
    {
        if (!_prototypeManager.TryIndex<EntityPrototype>(entry.PrototypeId, out var prototype))
            return null;

        return prototype.TryGetComponent<GunComponent>(out var gun, _componentFactory)
               && gun.ExamineCaliber is { } caliber
            ? Loc.GetString(caliber)
            : null;
    }

    /// <summary>
    ///     Weapon class ("pistol", "shotgun"...) from the prototype, localized so
    ///     the order matches the class shown in the detail pane.
    /// </summary>
    private string? GetWeaponClassKey(WeaponRegistryEntry entry)
    {
        if (!_prototypeManager.TryIndex<EntityPrototype>(entry.PrototypeId, out var prototype))
            return null;

        return prototype.TryGetComponent<NFWeaponDetailsComponent>(out var details, _componentFactory)
               && details.Class is { } weaponClass
            ? Loc.GetString(weaponClass)
            : null;
    }

    /// <summary>Opens the sorting window right under the filter button.</summary>
    private void OpenFilterPopup()
    {
        _filterPopup.SetActiveMode(_sortMode);
        _filterPopup.Open(GetFilterPopupBox());
    }

    /// <summary>
    ///     Where the sorting window appears: under the button, right-aligned with
    ///     it, so it does not stick out of the window. The UI manager clamps the
    ///     final position anyway, so there is no manual fitting to do here.
    /// </summary>
    private UIBox2 GetFilterPopupBox()
    {
        var width = Math.Max(_filterPopup.MinSize.X, _filterPopup.MinWidth);
        var height = Math.Max(_filterPopup.MinSize.Y, _filterPopup.MinHeight);

        var buttonBox = UIBox2.FromDimensions(RegistryFilterButton.GlobalPosition, RegistryFilterButton.Size);
        return UIBox2.FromDimensions(new(buttonBox.Right - width, buttonBox.Bottom), new(width, height));
    }

    /// <summary>The player picked an order in the sorting window.</summary>
    private void OnSortModeSelected(WeaponRegistrySortMode mode)
    {
        if (_sortMode != mode)
        {
            _sortMode = mode;

            // The button says just "Filter", so without the tooltip there would be
            // no way to tell what the list is currently sorted by.
            UpdateFilterButtonTooltip();
            RenderRegistry(BuildList());
        }

        _filterPopup.Close();
    }

    private void UpdateFilterButtonTooltip() =>
        RegistryFilterButton.ToolTip = Loc.GetString("weapon-registry-filter-tooltip",
            ("mode", Loc.GetString(_sortMode.GetSortLabel())));

    /// <summary>Entry value as it is shown to the player: a dash when it has none.</summary>
    private static string DisplayOrDash(string? value) =>
        String.IsNullOrWhiteSpace(value) ? MissingValueText : value;

    /// <summary>
    ///     Called when the program UI is put into the UI tree. The sorting window
    ///     is parented to the UI modal root, not to us, so it is re-attached here if
    ///     this fragment ever comes back after leaving the tree.
    /// </summary>
    protected override void EnteredTree()
    {
        base.EnteredTree();

        if (_filterPopup.Parent == null)
            UserInterfaceManager.ModalRoot.AddChild(_filterPopup);
    }

    /// <summary>
    ///     The program UI left the tree (the PDA window was closed, or the player
    ///     switched to another program). Without closing the sorting window here it
    ///     would stay floating on the screen, because it belongs to the UI modal
    ///     root rather than to this fragment.
    ///     Order matters: Close first (it also pops the window off the modal stack),
    ///     only then detach it.
    /// </summary>
    protected override void ExitedTree()
    {
        base.ExitedTree();

        _filterPopup.Close();
        _filterPopup.Orphan();
    }

    private void OnRegistrySearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        // args.Text, not RegistrySearchBar.Text: the event args carry the exact
        // value at the moment of the event, which is the honest source here.
        // A new filter means a new result list, so we always go back to its first page.
        _page = 0;
        RenderRegistry(BuildList());
    }

    /// <summary>
    ///     Draws the CURRENT PAGE of the given subset of entries and picks the right
    ///     "empty" message: the registry has no weapons at all vs. the filter
    ///     matched nothing.
    /// </summary>
    private void RenderRegistry(List<WeaponRegistryEntry> toShow)
    {
        RegistryList.GenerateItem = GenerateRegistryItem;
        RegistryList.ItemPressed = OnRegistryItemSelected;

        // Pagination is a plain slice of the received order: the server already
        // sorted the snapshot by the moment a weapon appeared in the registry
        // (newest first), so paging can never shuffle anything.
        var pageCount = Math.Max(1, (int) Math.Ceiling(toShow.Count / (double) PageSize));
        _page = Math.Clamp(_page, 0, pageCount - 1);
        var pageStart = _page * PageSize;
        var pageEntries = toShow.GetRange(pageStart, Math.Min(PageSize, toShow.Count - pageStart));

        var dataList = new List<ListData>();
        foreach (var entry in pageEntries)
            dataList.Add(new WeaponRegistryListData(entry));
        RegistryList.PopulateList(dataList);

        var empty = toShow.Count == 0;
        var filterActive = !String.IsNullOrWhiteSpace(RegistrySearchBar.Text);
        NoRegistryEntries.Visible = empty && !filterActive;
        NoRegistryMatches.Visible = empty && filterActive;
        RegistryList.Visible = !empty;

        // The pager is shown for any non-empty list (so the player can always see
        // which page they are on) and the arrows are greyed out at the edges.
        RegistryPager.Visible = !empty;
        RegistryPrevPageButton.Disabled = _page <= 0;
        RegistryNextPageButton.Disabled = _page >= pageCount - 1;
        RegistryPageLabel.Text = Loc.GetString("weapon-registry-page",
            ("page", _page + 1),
            ("total", pageCount));

        if (empty)
        {
            RegistryDetail.Visible = false;
            _selectedSerial = null;
        }
    }

    /// <summary>
    ///     Moves the current page. RenderRegistry clamps the result and refreshes
    ///     the pager, so this method needs no bounds check of its own.
    /// </summary>
    private void ChangePage(int delta)
    {
        _page += delta;
        RenderRegistry(BuildList());
    }

    private void OnRegistryItemSelected(BaseButton.ButtonEventArgs args, ListData data)
    {
        if (data is not WeaponRegistryListData(var entry))
            return;

        _selectedSerial = entry.Serial;
        RenderRegistryDetail(entry);
    }

    private void RenderRegistryDetail(WeaponRegistryEntry entry)
    {
        DetailWeapon.SetMessage(BuildMessage("weapon-registry-detail-weapon", ("name", DisplayOrDash(entry.Name))));
        DetailSerial.SetMessage(BuildMessage("weapon-registry-detail-serial", ("serial", entry.Serial)));
        DetailOrigin.SetMessage(entry.Origin == null
            ? BuildMessage("weapon-registry-detail-origin-unset")
            : BuildMessage("weapon-registry-detail-origin", ("origin", Loc.GetString(entry.Origin))));
        DetailOwner.SetMessage(entry.Owner == null
            ? BuildMessage("weapon-registry-detail-owner-unset")
            : BuildMessage("weapon-registry-detail-owner-set", ("owner", entry.Owner)));

        // Read-only: the owner edit field lives only in the weapon registration console.
        RegistryDetail.Visible = true;
    }

    private void GenerateRegistryItem(ListData data, ListContainerButton button)
    {
        if (data is not WeaponRegistryListData(var entry))
            return;

        // Weapon icon on the left, taken from the entity prototype (same pattern
        // the market menu uses). The icon lives INSIDE the row button, so clicking
        // it selects the entry — the whole row is one clickable button.
        // The box is ALWAYS IconBoxSize and the texture is stretched to fill it
        // exactly: a weapon whose sprite is bigger than the default one (a grenade
        // launcher) is scaled down, a smaller sprite is scaled up, a scaled sprite
        // is drawn at the default size regardless. SetSize wins over the texture's
        // own size, so the row height never depends on the sprite.
        var icon = new TextureRect
        {
            Stretch = TextureRect.StretchMode.Scale,
            SetSize = new(IconBoxSize, IconBoxSize),
            VerticalAlignment = VAlignment.Center,
            Margin = new(2f, 2f, 6f, 2f),
        };
        if (_prototypeManager.TryIndex<EntityPrototype>(entry.PrototypeId, out var prototype)
            && prototype.TryGetComponent(out SpriteComponent? sprite, _componentFactory))
        {
            icon.Texture = sprite.Icon?.Default;
        }

        // Show the serial number and the weapon name as stacked lines so both stay
        // readable inside the 192px row: line 1 = serial, line 2 = weapon name,
        // line 3 = owner (or a placeholder dash when there is none).
        // The third line is unconditional on purpose — see NoOwnerPlaceholder.
        var texts = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            Margin = new(2f, 2f, 8f, 2f),
        };

        // 1st line: serial number.
        texts.AddChild(new Label() { Text = entry.Serial, StyleClasses = { "LabelSmall" } });

        // 2nd line: weapon name. A dash when the entry has no name — such entries
        // are also pushed to the bottom by the sorting (see CompareKeys).
        var nameLabel = new Label()
        {
            Text = DisplayOrDash(entry.Name),
            ClipText = true,
            HorizontalExpand = true,
        };
        nameLabel.AddStyleClass("LabelSmall");
        texts.AddChild(nameLabel);

        // 3rd line: owner, small gray. The tooltip carries the full name because
        // the row is only 192px wide and the label clips.
        var ownerLabel = new Label()
        {
            Text = entry.Owner ?? NoOwnerPlaceholder,
            ClipText = true,
            ToolTip = entry.Owner,
            StyleClasses = { "LabelSmall" },
            FontColorOverride = Color.DarkGray,
        };
        texts.AddChild(ownerLabel);

        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        row.AddChild(icon);
        row.AddChild(texts);
        button.AddChild(row);
        button.AddStyleClass(ListContainer.StyleClassListContainerButton);

        if (entry.Serial.Equals(_selectedSerial))
        {
            button.Pressed = true;
            // Same workaround as the wanted list: Pressed change does not raise the event.
            OnRegistryItemSelected(
                new(button, new(new(), BoundKeyState.Down, new(), false, new(), new())),
                data);
        }
    }

    private FormattedMessage BuildMessage(string fluentId, params (string, object)[] args)
    {
        var msg = new FormattedMessage();
        msg.AddMarkupPermissive(Loc.GetString(fluentId, args));
        return msg;
    }
}

internal record WeaponRegistryListData(WeaponRegistryEntry Entry) : ListData;

