using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._radiant.WeaponSerial;

/// <summary>
///     Small sorting window of the OSK weapon registry program. It floats over the
///     PDA window (the fragment parents it to the UI modal root) and lets the
///     player pick the order of the list.
///     Analogy: a paper slip you put on top of the folder to choose how the cards
///     inside are sorted — pick one, the slip is gone, the folder is re-sorted.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WeaponRegistryFilterPopup : Popup
{
    /// <summary>
    ///     Raised when the player picks an order. The caller applies it and closes
    ///     the window; the popup deliberately does not close itself, so the owner
    ///     of the list stays in charge of that.
    /// </summary>
    public event Action<WeaponRegistrySortMode>? OnSortSelected;

    private readonly Dictionary<WeaponRegistrySortMode, Button> _buttons = new();

    public WeaponRegistryFilterPopup()
    {
        RobustXamlLoader.Load(this);

        // One toggle button per order. ToggleMode plus a shared ButtonGroup makes
        // the active order look pressed and unpresses the previous one by itself,
        // which is exactly the "radio list" the player expects here.
        var group = new ButtonGroup();

        foreach (var mode in Enum.GetValues<WeaponRegistrySortMode>())
        {
            // Captured per iteration: a closure over the loop variable would give
            // every button the LAST mode.
            var selectedMode = mode;

            var button = new Button
            {
                Text = Loc.GetString(selectedMode.GetSortLabel()),
                ToggleMode = true,
                Group = group,
                HorizontalExpand = true,
            };

            button.OnPressed += _ => OnSortSelected?.Invoke(selectedMode);
            _buttons[selectedMode] = button;
            OptionsContainer.AddChild(button);
        }
    }

    /// <summary>
    ///     Shows which order the list is in right now. Called every time the window
    ///     opens: the pressed state of the buttons is not part of the game state,
    ///     so it has to be restored explicitly.
    /// </summary>
    public void SetActiveMode(WeaponRegistrySortMode mode)
    {
        if (_buttons.TryGetValue(mode, out var button))
            button.Pressed = true;
    }
}
